### ISSUE TITLE
Alternative to this script

### ISSUE THREAD

**Issue by intelliot** [trustline-inc/xrp-faucet#1]
Your xrp-faucet is a fun script. I have one question and one informational idea to share:

1. Why do you need more than 1,000 test XRP?

2. There is an (undocumented) Testnet Faucet API:

Fund a specified account:
```
curl --header "Content-Type: application/json" -X POST https://faucet.altnet.rippletest.net/accounts --data '{"destination": "<address here>", "xrpAmount": "15000"}'
```

- Replace `<address here>` with the address to fund. This parameter is optional; if not specified, the faucet will create a new random account.
- `xrpAmount` is optional (current default: "1000" - may change in the future), and the max is 1,000,000 Testnet XRP. This example sends 15,000.
- The amount that was sent is in the `amount` field of the response.
- X-addresses are supported and they must start with `T` (indicating a Testnet X-address).
- The "Content-Type: application/json" header is required.
- The specified account can pre-exist on the ledger. If it doesn't exist, the funding transaction causes the account to be created.

**Comment by mrosendin** [comment]
Hi @intelliot 

We are in fact using this exact API, but it's really helpful to know that it accepts a destination and an amount parameter.

To answer your question...

We have a mobile app that's running on the testnet and we have 5 thousand beta-testers. To make it easy for our users to test, we fund each testnet account with 60 XRP. Each account requires the 20 XRP reserve fee, plus additional XRP for setting up a multi-signature transaction and creation of a trust line. Our testnet wallet was quickly depleted of 10,000 XRP when we first started onboarding users, so we made this script in lieu of using the RippleX portal, which only allows 1,000 XRP.

That being said, we will just call this API going forward. Thank you for bringing this to our attention.
